### ISSUE TITLE
I've tried to pack the gtk-demo in lgi

### ISSUE THREAD

**Issue by eriksank** [ers35/luastatic#14]
I have tried to build a static executable from gtk-demo from https://github.com/pavouk/lgi.

$ cd lgi/samples/gtk-demo
$ luastatic main.lua  /usr/local/share/lua/5.3/lgi.lua \
	 $(find /usr/local/share/lua/5.3/lgi -type f) \
	*.lua \
	/usr/local/lib/liblua.a  /home/vm/lgi/lgi/lgi.a \
	-I/usr/local/include $(pkg-config --libs \
	gobject-introspection-1.0 gmodule-2.0 libffi)
cc -Os main.lua.c /home/vm/lgi/lgi/lgi.a /usr/local/lib/liblua.a -rdynamic -lm -ldl -o main -I/usr/local/include -lgirepository-1.0 -lgobject-2.0 -Wl,--export-dynamic -lgmodule-2.0 -pthread -lglib-2.0 -lffi

In the build vm, the resulting executable works fine, but in another vm:

$ ./main
[string "main"]:30: module 'lgi' not found:
	no field package.preload['lgi']
	no module 'lgi' in luastatic bundle
	no file '/usr/local/share/lua/5.3/lgi.lua'
	no file '/usr/local/share/lua/5.3/lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.lua'
	no file '/usr/local/lib/lua/5.3/lgi/init.lua'
	no file './lgi.lua'
	no file './lgi/init.lua'
	no file '/usr/local/lib/lua/5.3/lgi.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lgi.so'
stack traceback:
	[C]: in function 'require'
	[string "main"]:30: in local 'func'
	[string "main"]:36: in main chunk

It cannot find /usr/local/share/lua/5.3/lgi.lua, even though it was specified as a dependency. Could it be a problem with nested modules? lgi.lua requires lgi.init which comes from a subdirectory in /usr/local/lib. Can luastatic handle these subdirectories too? Dunno, something seems to go wrong ...

**Comment by mpeterv** [comment]
Luastatic needs to know what module names correspond to what files. It's not clear that it should be possible to require file given as `/usr/local/share/lua/5.3/lgi.lua` with `require "lgi"`, because target Lua may have a different `package.path`. So Luastatic uses a simple approach: when a path for a Lua module is given, it interprets it as a relative path: strips the extension, replaces slashes with dots and makes the result it's canonical module name. You passed it `/usr/local/share/lua/5.3/lgi.lua` so in the bundle you'd need to call `require(".usr.local.share.lua.5.3.lgi")` to get it. Move the file into current directory and pass `lgi.lua` to make it work.

**Comment by mpeterv** [comment]
This is basically #5.

**Comment by eriksank** [comment]
You are right, moving the lgi package into the gtk-demo folder solves the problem. The luastatic packaging works fine now. There is just one problem with the demo program itself. It loads the demo-*.lua files from its own directory, to show it as text inside the demo. So, I still need to deploy those too. That is not an issue with luastatic, though. The packaging fundamentally works fine now. I thought it wouldn't because lgi uses some dynamic mapping magic to be able to call gtk3 functions using gobject-introspection. It thought that this would go haywire with luastatic, but it doesn't. it works really well. After stripping and using upx, the entire demo fits into 220K:

ls -lh main
-rwxr-xr-x 1 vm vm 220K Aug 12 07:18 main

Luastatic seems fantastically usable for deploying gtk3 user interfaces. Great work!
